config/routes.rb
Rails.application.routes.draw do
  get 'google/callback'

  get 'google/redirect'

  get 'google/jobs'

  resources :configurations
  resources :app_configurations
  get 'taghere/menu'

  get 'taghere/set_table'
  get 'taghere/order'
  get 'taghere/balance'
  get 'taghere/garcon'
  get 'taghere/success'

  resources :employees do
    member do
      get "adiantamento"
    end
    collection do
      get "imprimir_adiantamento"
      get "deletar_vale"
    end
  end
  resources :couverts
  get 'garcon/chamadas'

  get 'garcon/pedido'

  get 'garcon/fechar_conta'

  devise_for :users
  resources :users
  resources :cancel_reasons
  resources :measures
  resources :pedido_extras
  resources :extras
  resources :payment_types
  resources :client_phones
  resources :clients do
    collection do
      get "check_cpf"
      get "credito"
    end
    member do
      get "crediario"
    end
  end
  resources :providers do
    collection do
      get "check_cpf"
    end
  end
  resources :ingredient_entraces
  resources :entrances
  resources :comandas do
    member do
      get "novo_pedido"
      get "concluir"
      get "pedido_simples"
      get "imprimir"
      get "imprimir_nogroup"
      get "calcular_taxa"
      get "inserir_couvert"
      get "fechar"
      get "calcular_desconto"

    end
    collection do
      get "enviar_pedido"
      get "dashboard"
      get "simples"
      get "caixa"
    end
  end
  resources :flavor_orders
  resources :product_orders do
    collection do
      get "atualiza_pedido"
    end
    member do
      get "change_comanda"
      get "cancelar"
      get "imprimir"
      get "concluir"
    end
  end
  resources :orders do
    member do
      get "change_comanda"
      get "cancelar"
      get "print"
    end
  end
  resources :dining_tables do
    collection do
      get "home"
    end
    member do
      get "comandas"
      get "unificar_comandas"
    end
  end
  resources :promotion_flavor_sizes
  resources :promotions
  resources :flavor_sizes do
    collection do
      get "produtos_por_categoria"
      get "retorna_sabores"
      get "retorna_adicionais"
    end
  end
  resources :ingredient_flavors
  resources :flavors
  resources :product_sizes
  resources :products
  resources :areas do
    collection do
      get "atualiza"
    end
  end
  resources :subgroups
  resources :product_groups
  resources :ingredients

  resources :sage_one do
    collection do
      get "url_callback"
    end
  end

  root "dining_tables#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id             :integer          not null, primary key
#  name           :string
#  address        :string
#  pis            :string
#  phone          :string
#  cpf            :string
#  rg             :string
#  hiring_date    :date
#  demission_date :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Employee < ApplicationRecord
  has_paper_trail
  has_many :down_payments

  accepts_nested_attributes_for :down_payments, allow_destroy: true

  validates :name, :address, :cpf, :phone, presence: true

  def to_s
    self.name
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :adiantamento]

  # GET /employees
  def index
    @q = Employee.all.ransack(params[:q])
    @employees = @q.result.page(params[:page])
  end

  # GET /employees/1
  def show
  end

  def imprimir_adiantamento
    @pagamento = DownPayment.find(params[:pagamento])
    respond_to do |format|
      format.html{render layout: false}
      format.text
    end
  end

  def deletar_vale
    vale = DownPayment.find(params[:vale])
    vale.destroy
    redirect_to vale.employee
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  def adiantamento
    DownPayment.create(value: params[:valor], data: params[:data], employee: @employee, note: params[:note])
    redirect_to @employee
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee, notice: 'Funcionário criado com sucesso!'
    else
      render :new
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Funcionário atualizado com sucesso!'
    else
      render :edit
    end
  end

  # DELETE /employees/1
  def destroy
    begin
      @employee.destroy
      redirect_to employees_url, notice: 'Funcionário excluído com sucesso'
    rescue
      redirect_to employees_url, alert: 'Funcionário já está vinculado!'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def employee_params
      params.require(:employee).permit(:name, :address, :pis, :phone, :cpf, :rg, :hiring_date, :demission_date)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5>Resolva os problemas a seguir antes de Salvar:</h5>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
    
  </div>

  <div class="input-field">

    <%= f.label :address, "Endereço" %>
    <%= f.text_field :address %>
    
  </div>

  <div class="input-field">

    <%= f.label :pis %>
    <%= f.text_field :pis %>
    
  </div>

  <div class="input-field">

    <%= f.label :phone, "Telefone" %>
    <%= f.text_field :phone, class:"telefone" %>
    
  </div>

  <div class="input-field">

    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
    
  </div>

  <!--<div class="input-field">

    <%#= f.label :rg %>
    <%#= f.text_field :rg %>

  </div>-->

  <div class="input-field">
    <%= f.label :hiring_date, "Contratação" %>
    <%= f.date_field :hiring_date, class:"datepicker" %>
  </div>

  <div class="input-field">

    <%= f.label :demission_date, "Demissão" %>
    <%= f.date_field :demission_date, class:"datepicker" %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn",target:"_self" %>
    <%= link_to "Voltar", employees_path, class:"btn",target:"_self" %>
  </div>
<% end %>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $(".telefone").mask("(99) 99999-999?9");
    });
</script>

app/views/employees/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição - Funcionários</h4>
</div>

<%= render 'form', employee: @employee %>

app/views/employees/imprimir_adiantamento.html.erb
<h4 style="text-align: center">VALE</h4>
<p>
  Funcionário: <%= @pagamento.employee %>
</p>
<p>CPF: <%= @pagamento.employee.cpf %></p>
<p>Valor: <%= number_to_currency(@pagamento.value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
<p>Observação: <%= @pagamento.note %></p>
<p>Data: <%= @pagamento.data %></p>
<div style="height: 50px"></div>
<hr>
<p style="text-align: center">Assinatura</p>



<div style="height: 100px"></div>
<hr>

<h4 style="text-align: center">VALE</h4>
<p>
  Funcionário: <%= @pagamento.employee %>
</p>
<p>CPF: <%= @pagamento.employee.cpf %></p>
<p>Valor: <%= number_to_currency(@pagamento.value, unit: "R$ ", separator: ",", delimiter: ".") %></p>
<p>Observação: <%= @pagamento.note %></p>
<p>Data: <%= @pagamento.data %></p>
<div style="height: 50px"></div>
<hr>
<p style="text-align: center">Assinatura</p>

<script type="text/javascript" charset="utf-8">
    window.print();
    window.close();
</script>

app/views/employees/index.html.erb
<h1 class="center-align"><b>Funcionários</b></h1>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <%= f.text_field :name_cont, placeholder: "Pesquisar..." %>
          <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to '+ Cadastrar', new_employee_path, class:"btn", target: "_self" %>
<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Pis</th>
    <th>Cpf</th>
    <th>Telefone</th>
    <th>Contratação</th>
    <th>Demissão</th>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
      <tr>

        <td><%= link_to employee.name,employee, target:"_self" %></td>
        <td><%= employee.pis %></td>
        <td><%= employee.cpf %></td>
        <td><%= employee.phone %></td>

        <td><%= employee.hiring_date %></td>
        <td><%= employee.demission_date %></td>
        <td><%= link_to 'Excluir', employee, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@employees)  %>
</div>

<%= link_to '+ Cadastrar', new_employee_path, class:"btn", target: "_self" %>

app/views/employees/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro - Funcionários</h4>
</div>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<div class="card-panel">

  <div class="row">
    <p>
      <strong>Nome:</strong>
      <%= @employee.name %>
    </p>
  </div>

  <div class="row">
    <div class="col s4">
      <p>
        <strong>Pis:</strong>
        <%= @employee.pis %>
      </p>
    </div>
    <div class="col s4">
      <p>
        <strong>Cpf:</strong>
        <%= @employee.cpf %>
      </p>
    </div>
    <!--<div class="col s4">
      <p>
        <strong>Rg:</strong>
        <%#= @employee.rg %>
      </p>
    </div>-->
  </div>

  <p>
    <strong>Telefone:</strong>
    <%= @employee.phone %>
  </p>
  <p>
    <strong>Endereço:</strong>
    <%= @employee.address %>
  </p>

  <p>
    <strong>Contratação:</strong>
    <%= @employee.hiring_date %>
  </p>

  <p>
    <strong>Demissão:</strong>
    <%= @employee.demission_date %>
  </p>

  <div class="card">
    <div class="card-content">
      <span class="card-title"><b>Vales</b></span>
      <table>
        <tr>
          <th>Valor</th>
          <th>Observação</th>
          <th>Data</th>
        </tr>
        <% @employee.down_payments.each do |p| %>
            <tr>
              <td><%= number_to_currency(p.value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
              <td><%= p.note %></td>
              <td><%= p.data %></td>
              <td>
                <a href="/employees/imprimir_adiantamento?pagamento=<%= p.id %>" class="waves-effect waves-cyan" target="_blank">
                  <i class="fa fa-print"></i>
                </a>
              </td>
              <td>
              <td><%= link_to 'Excluir', deletar_vale_employees_path(vale: p.id) %></td>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
    <a href="" onclick="open_modal('adiantamento');" class="btn">Vale</a>
    </a>
  </div>

  <div id="adiantamento" class="modal">
    <div class="modal-content">
      <h4>Novo Vale</h4>
      <%= form_tag(adiantamento_employee_path(@employee), method: :get) do  %>
          <div class="input">
            <%= label :valor, "Valor" %>
            <%= text_field_tag :valor%>

          </div>
          <div class="input">
            <%= label :note, "Observação" %>
            <%= text_field_tag :note%>

          </div>
          <div class="input-field">
            <%= label :data, "Data" %>
            <%= date_field_tag :data,{}, {class:"datepicker"}%>

          </div>
          <br>
          <%= submit_tag "Salvar", class:"modal-action modal-close  btn " %>
      <% end %>
    </div>
  </div>

</div>
<%= link_to 'Voltar', employees_path, class:"btn",target:"_self" %>
<script type="text/javascript">
    function open_modal(id)
    {
        $("#"+id).openModal();
    }


</script>