config/routes.rb
Rails.application.routes.draw do
  get 'google/callback'

  get 'google/redirect'

  get 'google/jobs'

  resources :configurations
  resources :app_configurations
  get 'taghere/menu'

  get 'taghere/set_table'
  get 'taghere/order'
  get 'taghere/balance'
  get 'taghere/garcon'
  get 'taghere/success'

  resources :employees do
    member do
      get "adiantamento"
    end
    collection do
      get "imprimir_adiantamento"
      get "deletar_vale"
    end
  end
  resources :couverts
  get 'garcon/chamadas'

  get 'garcon/pedido'

  get 'garcon/fechar_conta'

  devise_for :users
  resources :users
  resources :cancel_reasons
  resources :measures
  resources :pedido_extras
  resources :extras
  resources :payment_types
  resources :client_phones
  resources :clients do
    collection do
      get "check_cpf"
      get "credito"
    end
    member do
      get "crediario"
    end
  end
  resources :providers do
    collection do
      get "check_cpf"
    end
  end
  resources :ingredient_entraces
  resources :entrances
  resources :comandas do
    member do
      get "novo_pedido"
      get "concluir"
      get "pedido_simples"
      get "imprimir"
      get "imprimir_nogroup"
      get "calcular_taxa"
      get "inserir_couvert"
      get "fechar"
      get "calcular_desconto"

    end
    collection do
      get "enviar_pedido"
      get "dashboard"
      get "simples"
      get "caixa"
    end
  end
  resources :flavor_orders
  resources :product_orders do
    collection do
      get "atualiza_pedido"
    end
    member do
      get "change_comanda"
      get "cancelar"
      get "imprimir"
      get "concluir"
    end
  end
  resources :orders do
    member do
      get "change_comanda"
      get "cancelar"
      get "print"
    end
  end
  resources :dining_tables do
    collection do
      get "home"
    end
    member do
      get "comandas"
      get "unificar_comandas"
    end
  end
  resources :promotion_flavor_sizes
  resources :promotions
  resources :flavor_sizes do
    collection do
      get "produtos_por_categoria"
      get "retorna_sabores"
      get "retorna_adicionais"
    end
  end
  resources :ingredient_flavors
  resources :flavors
  resources :product_sizes
  resources :products
  resources :areas do
    collection do
      get "atualiza"
    end
  end
  resources :subgroups
  resources :product_groups
  resources :ingredients

  resources :sage_one do
    collection do
      get "url_callback"
    end
  end

  root "dining_tables#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comanda.rb
# == Schema Information
#
# Table name: comandas
#
#  id               :integer          not null, primary key
#  dining_table_id  :integer
#  tipo             :string
#  entrega          :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  status           :boolean
#  client_id        :integer
#  couvert_value    :decimal(, )
#  couvert_quantity :integer
#  tax              :decimal(, )
#  fechada          :boolean
#  contaazul_id     :string
#  desconto         :decimal(, )
#  who_close        :integer
#
# Indexes
#
#  index_comandas_on_client_id        (client_id)
#  index_comandas_on_dining_table_id  (dining_table_id)
#
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id)
#  fk_rails_...  (dining_table_id => dining_tables.id)
#

class Comanda < ApplicationRecord
  has_paper_trail
  belongs_to :dining_table , optional: true
  belongs_to :client , optional: true
  has_many :orders, dependent: :destroy
  has_many :product_orders, through: :orders
  has_many :flavor_orders, through: :product_orders
  has_many :order_payments, dependent: :destroy
  has_many :flavor_sizes, through: :product_orders
  belongs_to :user, class_name: "User", foreign_key: :who_close,optional: true

  accepts_nested_attributes_for :orders, allow_destroy: true
  accepts_nested_attributes_for :product_orders, allow_destroy: true
  accepts_nested_attributes_for :flavor_orders, allow_destroy: true
  accepts_nested_attributes_for :order_payments, allow_destroy: true

  extend Enumerize

  enumerize :tipo, in: [:garcom, :app, :delivery,:caixa], predicates: true

  validate :check_payments
  before_validation :set_tax

  def sync_contaazul
    begin
      if self.contaazul_id.present?
        update_on_contaazul
      else
        create_on_contaazul
      end
    rescue
    end
  end

  def print_cloud
    if self.fechada
      begin
        area = Area.find_by_name("Caixa")
        if area.printer.present?
            PrintApi.send_print(
                "http://boamassa.herokuapp.com/comandas/#{self.id}/imprimir.txt",
                area.printer
            )
        end
      rescue
      end
    end

  end

  def update_on_contaazul
    params = contaazul_params
    response = ContaazulApi.call(:put, "/v1/sales/#{self.contaazul_id}", params)
  end

  def create_on_contaazul
    params = contaazul_params
    response = ContaazulApi.call(:post, "/v1/sales", params)
    self.contaazul_id = response[:id]
    response
  end

  def contaazul_params

    products = product_orders.where.not(status: :cancelado).map do |po|
      {
        "description": po.flavor_size.to_s,
        "quantity": po.quantity,
        "value": po.value,
        "product_id": "d4f1ace9-9d29-4cca-8219-71325679cbda"
      }
    end

    payments = order_payments.map do |op|
      {
      "number": op.id,
      "value": op.value,
      "due_date": DateTime.now,
      "status": "ACQUITTED"
      }
    end
    params = {
      "number": self.id,
      "status": "COMMITTED",
      "emission": DateTime.now,
      "payment": {
          "type": "CASH",
          "installments": payments
      },
      "services": [
        {
            "description": "Couvert",
            "quantity": self.couvert_quantity || 1,
            "value": self.couvert_value || 0,
            "service_id": "161ed420-d2f7-49d9-8955-4773e171dd16",
        },
        {
            "description": "Taxa de Serviço",
            "quantity": 1,
            "value": self.tax || 0,
            "service_id": "5254257a-569b-40a1-b719-7e92942c11b9",
        }
      ],
      "products": products
    }
    if client.present? and client.contaazul_id.present?
      params[:customer_id]= client.contaazul_id
    else
      params[:customer_id]= "83f16edc-5f9e-457f-868a-638f52febd8a"
    end
    params
  end
  def self.actives
    where(status: false)
  end

  def check_payments
    if self.status
      total_pago = self.order_payments.sum(&:value)
      total = self.product_orders.where.not(status: :cancelado).sum(&:value) + (self.tax.round(2) || 0) + couvert_calculado - (self.desconto || 0)
      if total_pago != total
        errors.add(:base,"Confira os pagamentos!")
      end
      errors.blank?
    end

  end

  def total_orders
    product_orders.where.not(status: :cancelado).sum(&:value)
  end

  def set_tax
    if garcom?
      self.tax = total_orders * 0.1
    end
  end

  def to_s
    self.id
  end

  def couvert_calculado
    (self.couvert_value || 0 ) * (self.couvert_quantity || 1)
  end

  def print?
    (caixa? and entrega) or !caixa?
  end


end

app/controllers/comandas_controller.rb
class ComandasController < ApplicationController
  before_action :authenticate_user!, except: [:imprimir]
  load_and_authorize_resource except: [:imprimir]
  before_action :set_comanda, only: [:show, :edit, :update, :destroy,:novo_pedido,:concluir,:imprimir,:calcular_taxa,:inserir_couvert,:fechar,:calcular_desconto]
  before_action :set_combos, only: [:new, :edit, :create,:update]

  # GET /comandas
  def index
    if params[:receber].present?
      @q = Comanda.where("id in (?)",params[:receber].tr("[]",'').split(",")).order(id: :desc).ransack(params[:q])
    else
      @q = Comanda.all.order(id: :desc).ransack(params[:q])
    end

    @comandas = @q.result.page(params[:page])
  end

  def caixa
    @q = Comanda.where(fechada: true, status: false).ransack(params[:q])
    @comandas = @q.result.page(params[:page])
  end

  # GET /comandas/1
  def show
    @comandas = Comanda.where(status: false).sort_by(&:id).map{|a| ["Mesa: #{a.dining_table} - Comanda: #{a.id}",a.id]}
    @motivos = CancelReason.all.sort_by(&:name).map{|a| [a.name,a.id]}
    #@flavors = FlavorSize.includes(:flavor,:product_size,:product).where(product_sizes: {quantity_flavors: 0}).where(active:true, visible:true).sort_by{|a| a.product.name}.map{|a| ["#{a.product.name} - #{a.flavor} - #{a.product_size.name}", a.id]}
    @flavors = FlavorSize.includes(:flavor,:product_size,:product).where(active:true, visible:true).sort_by{|a| a.product.name}.map{|a| ["#{a.product.name} - #{a.flavor} - #{a.product_size.name}", a.id]}
    @clients = Client.all.sort_by{|e| e.nome}.map{|a| [a,a.id]}
    @payments = PaymentType.all.sort_by{|e| e.name}.map{|a| [a,a.id]}
    @payments_value = @comanda.order_payments.sum(:value)
  end

  def inserir_couvert
    @comanda.couvert_value = params[:valor]
    @comanda.couvert_quantity = params[:quantity]
    @comanda.save
    redirect_to @comanda
  end

  def imprimir
    @product_orders = @comanda.product_orders.where.not(status: :cancelado)
    @crediarios = @comanda.order_payments.includes(:payment_type).where(payment_types: {name: 'Crediário'})
    #@comanda.print_cloud
    respond_to do |format|
      format.html {render layout: false}
      format.text
      format.pdf do
        render pdf: "teste"
      end
    end
  end

  def imprimir_nogroup
    @product_orders = @comanda.product_orders.where.not(status: :cancelado)
    respond_to do |format|
      format.html {render layout: false}
      format.text
      format.pdf do
        render pdf: "teste"
      end
    end
  end

  def simples
    @clients = Client.all.sort_by{|e| e.nome}.map{|a| [a,a.id]}
    @payments = PaymentType.all.sort_by{|e| e.name}.map{|a| [a,a.id]}
    @comanda = Comanda.new(tipo: :caixa, tax: 0,fechada: false)
    @comanda.orders.build
    @flavors = FlavorSize.includes(:flavor,:product_size,:product).where(active:true, visible:true).sort_by{|a| a.product.name}.map{|a| ["#{a.product.name} - #{a.flavor} - #{a.product_size.name}", a.id]}
  end

  def calcular_taxa
    if params[:no_tax].present?
      @comanda.tipo = :caixa
      @comanda.tax = 0
    else
      @comanda.tipo = :garcom
    end
    @comanda.set_tax
    @comanda.save
    redirect_to @comanda
  end

  def pedido_simples
    order = Order.create(comanda: @comanda, user: current_user)
    product_order = ProductOrder.create(flavor_size_id: params[:flavor_size_id], order: order, quantity: params[:quantity].gsub(',','.'))
    redirect_to @comanda
  end

  def calcular_desconto
    if params[:value].present?
      params[:value].sub! ',','.'
      begin
        couvert = @comanda.couvert_value * @comanda.couvert_quantity
      rescue
        couvert = 0
      end
      if params[:value].include? "%"
        @comanda.desconto = ((@comanda.product_orders.where.not(status: :cancelado).sum(&:value) + (@comanda.tax || 0) + couvert) / 100) * params[:value].to_f
      else
        @comanda.desconto = params[:value].to_f
      end
      @comanda.save
    end

    redirect_to @comanda

  end

  def dashboard
    if !params[:dia].present?
      @q = Comanda.ransack(params[:q])

    else
      @q = Comanda.where("date(created_at) = ?", DateTime.now.to_date).ransack(params[:q])
    end

    @comandas = @q.result

    @taxa = @comandas.sum{|a| a.tax}
    @recebido = @comandas.sum{|a| a.order_payments.sum(:value)}
    @areceber = @comandas.sum{|a| a.product_orders.where.not(status: :cancelado).sum(:value) + (a.couvert_calculado) + (a.tax || 0) - (a.desconto || 0)} - @recebido
    @comandas_areceber = []
    @comandas.each do |a|
      if (a.product_orders.where.not(status: :cancelado).sum(:value) + (a.couvert_calculado) + (a.tax || 0) - (a.desconto || 0)) != a.order_payments.sum(:value)
        @comandas_areceber << a.id
      end
    end
    @comandas_abertas = @comandas.where(status: false).count
    @comandas_concluidas = @comandas.where(status: true).count
    @pedidos = @comandas.sum{|a| a.orders.size}
    @pagamentos =  OrderPayment.where("comanda_id in (?)",@comandas.pluck(:id))
    orders = Order.where("comanda_id in (?)",@comandas.pluck(:id))
    @product_orders = ProductOrder.select("flavor_size_id").where("status <> 'cancelado' and order_id in (?) ",orders.pluck(:id)).order(2).group(:flavor_size_id).sum(:quantity)
    @mais_pedidos = FlavorSize.all.sort_by{|a| a.product_orders.sum(:quantity)}[1..5]
  end

  # GET /comandas/new
  def new
    if params[:table].present?
      @comanda = Comanda.new(dining_table_id: params[:table], tax: 0,fechada: false)
    else
      @comanda = Comanda.new(tax: 0,fechada: false)
    end

  end

  def  novo_pedido
    
  end

  # GET /comandas/1/edit
  def edit
  end

  # POST /comandas
  def create
    @comanda = Comanda.new(comanda_params)
    @comanda.status = false
    if @comanda.save
      if !params[:balcao].present?
        redirect_to novo_pedido_comanda_path(@comanda), notice: 'Comanda criada com sucesso!'
      else
        redirect_to @comanda
      end

    else
      render :new
    end
  end



  # PATCH/PUT /comandas/1
  def update

    if @comanda.update(comanda_params)
      redirect_to @comanda, notice: 'Comanda atualizada com sucesso!'
    else
      render :edit
    end
  end

  def fechar
    @comanda.fechada = params[:status]
    if params[:status] == "false"#verifica se está reabrindo para então remover o status de paga
      @comanda.status = false
    end
    @comanda.who_close = current_user.id
    @comanda.save
    @comanda.print_cloud
    redirect_to @comanda
  end

  def concluir
    @comanda.status = true
    @comanda.fechada = true
    if @comanda.save
      @comanda.orders.where("status <> 'cancelado' ").update(status: :concluido)
      @comanda.product_orders.where("product_orders.status <> 'cancelado' ").update(status: :concluido)
      @comanda.sync_contaazul
      @comanda.print_cloud
      if @comanda.dining_table.present?
        redirect_to comandas_dining_table_path(@comanda.dining_table)
      else
        redirect_to root_path
      end
    else
      redirect_to comanda_path(@comanda), alert: @comanda.errors.full_messages.to_sentence
    end



  end

  # DELETE /comandas/1
  def destroy
    @comanda.destroy
    redirect_to comandas_url, notice: 'Comanda excluída com sucesso!'
  end

  private
  def set_combos
    @clients = Client.all.sort_by{|e| e.nome}.map{|a| [a,a.id]}
    @payments = PaymentType.all.sort_by{|e| e.name}.map{|a| [a,a.id]}
    @flavors = FlavorSize.includes(:flavor,:product_size,:product).where(active:true, visible:true).sort_by{|a| a.product.name}.map{|a| ["#{a.product.name} - #{a.flavor} - #{a.product_size.name}", a.id]}
    @sabores = FlavorSize.includes(:flavor,:product_size,:product).where(active: true, visible: false).sort_by{|a| a.product.name}.map{|a| ["#{a.product.name} - #{a.flavor} - #{a.product_size.name}", a.id]}
    @mesas = DiningTable.all.order("NULLIF(regexp_replace(number, '\\D', '', 'g'), '')::int").map{|a| [a.number,a.id]}

  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comanda
      @comanda = Comanda.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comanda_params
      params.require(:comanda).permit(:dining_table_id,:desconto,:fechada,:tax, :tipo, :entrega,:client_id,:couvert_value, :couvert_quantity,
      orders_attributes:[:id,:comanda_id,:status,:delivery_time,:user_id,:_destroy,
        product_orders_attributes:[:id,:user_id,:flavor_size_id, :order_id, :quantity, :note, :status, :value, :_destroy,
          flavor_orders_attributes:[:id,:product_order_id,:flavor_size_id, :_destroy] ] ],
      order_payments_attributes:[:id,:payment_type_id,:value,:client_id,:paid,:comanda_id,:_destroy])
    end
end

app/helpers/comandas_helper.rb
module ComandasHelper
end

app/views/comandas/caixa.html.erb
<h1 class="center-align"><b>Comandas</b></h1>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <%# f.text_field :name_cont, placeholder: "Pesquisar..." %>
          <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>

<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Número</th>
    <th>Mesa</th>
    <th>Tipo</th>
    <th>Entrega</th>
    <th>Paga</th>
  </tr>
  </thead>

  <tbody>
  <% @comandas.sort_by(&:id ).reverse.each do |comanda| %>
      <tr>
        <td><%= link_to comanda,comanda %></td>
        <td><%= link_to comanda.dining_table,comanda.dining_table if comanda.dining_table.present?%></td>
        <td><%= comanda.tipo %></td>
        <td><%= comanda.entrega == true ? "SIM" : "NÃO" %></td>
        <td><%= comanda.status == true ? "SIM" : "NÃO" %></td>
        <td><%#= link_to 'Excluir', comanda, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@comandas)  %>
</div>

<%= link_to '+ Cadastrar', simples_comandas_path, class:"btn" %>

app/views/comandas/dashboard.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" r>
      Pesquisa
    </span>
    <div id="pesquisa" >
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
          <div class="row">
            <div class="col s12 l3">
              <label >Data Inicial</label>
              <%= f.datetime_field :created_at_gteq, placeholder: "Data Inícial"%>
            </div>
            <div class="col s12 l3">
              <label >Data Final</label>
              <%= f.datetime_field :created_at_lteq, placeholder: "Data Final" %>
            </div>
            <div class="col s12 l3">
              <label >Tipo</label>
              <%= f.select :tipo_eq, Comanda.tipo.options,{prompt:true},{class:"browser-default"} %>
            </div>
          </div>
          <%= f.submit "Filtrar", class:"btn" %>
          <%= link_to  "Limpar", dashboard_comandas_path, class:"btn", target:"_self" %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s12 l3">
    <%= link_to "/comandas?q%5Bstatus_eq%5D=false" do %>
    <div class="card gradient-45deg-red-pink gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">event_note</i>

        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= @comandas_abertas %></h5>
          <p class="no-margin">Comandas Abertas</p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col s12 l3">
    <%= link_to "/comandas?q%5Bstatus_eq%5D=true" do %>
    <div class="card gradient-45deg-green-teal gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">event_note</i>

        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= @comandas_concluidas %></h5>
          <p class="no-margin">Comandas Fechadas</p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col s12 l3">
    <div class="card gradient-45deg-light-blue-cyan gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">attach_money</i>
          <p class="no-margin">Recebido</p>
        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= number_to_currency(@recebido, unit: "R$ ", separator: ",", delimiter: ".") %></h5>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 l3">
    <%= link_to "/comandas?receber=#{@comandas_areceber}" do %>
    <div class="card gradient-45deg-amber-amber gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">attach_money</i>
          <p class="no-margin">A Receber</p>
        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= number_to_currency(@areceber, unit: "R$ ", separator: ",", delimiter: ".") %></h5>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>
<div class="row">
  <div class="col s12 l3">
    <div class="card gradient-45deg-light-blue-cyan gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">shopping_cart</i>
        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= @pedidos %></h5>
          <p class="no-margin">Pedidos</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 l3">
    <div class="card gradient-45deg-amber-amber gradient-shadow min-height-100 white-text">
      <div class="padding-4">
        <div class="col s7 m7">
          <i class="material-icons background-round mt-5">attach_money</i>
          <p class="no-margin">Taxa de Serviço</p>
        </div>
        <div class="col s5 m5 right-align">
          <h5 class="mb-0"><%= number_to_currency(@taxa, unit: "R$ ", separator: ",", delimiter: ".") %></h5>
        </div>
      </div>
    </div>
  </div>

</div>
<div class="row">
  <div class="col s12 l6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><b>Mais Pedidos</b></span>
        <table class="stipred">
          <thead>
          <th>#</th>
          <th>Produto</th>
          </thead>
          <tbody>
          <% @product_orders.first(5).each_with_index do |pedido, index| %>

              <tr>
                <td><%= index + 1 %></td>
                <td><%= FlavorSize.find(pedido[0]) %></td>
              </tr>
          <% end if @product_orders%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col s12 l6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><b>Pagamentos</b></span>
        <table class="stipred">
          <thead>
          <th>Pagamento</th>
          <th>Valor</th>
          </thead>
          <tbody>
          <% @pagamentos.group_by(&:payment_type).map do |payment_type,pagamentos| %>
              <tr>
                <td><%= payment_type %></td>
                <td><%= number_to_currency(pagamentos.sum{|a| a.value}, unit: "R$ ", separator: ",", delimiter: ".") %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/comandas/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição</h4>
</div>

<%= render 'form', comanda: @comanda %>

app/views/comandas/imprimir_nogroup.text.erb
  CANTINA BOAMASSA
  CNPJ: 10.734.874/0001-26
  602 SUL, AVENIDA LO 13 LOTE 17
  TELEFONE: 63 3225-1713
  www.cantinaboamassa.com.br

  *** PRÉ-CONTA ***

  MESA <%= @comanda.dining_table %>
  DATA: <%= Time.zone.now %>

  === PEDIDOS ===

  <% @product_orders.each do |product_order |  %>
  <%= "#{product_order.flavor_size}".upcase %>
  <%= product_order.quantity %> = <%= product_order.value %>


  <% end %>

  === ****** ===

  SUBTOTAL = <%= number_to_currency(total1 =  @comanda.product_orders.where.not(status: :cancelado).sum(&:value), unit: "R$ ", separator: ",", delimiter: ".") %>
  SERVIÇOS = <%= number_to_currency(total3 = (total1 * 0.1), unit: "R$ ", separator: ",", delimiter: ".") %>
  COUVERT  = <%= number_to_currency(total2 = @comanda.couvert_calculado, unit: "R$ ", separator: ",", delimiter: ".") %>
  TOTAL    = <%= number_to_currency(total1+total2+total3, unit: "R$ ", separator: ",", delimiter: ".") %>

  === ****** ===

  <%= @comanda.couvert_quantity || 1 %> PESSOA(S) * <%= number_to_currency( (total1+total2+total3)/ (@comanda.couvert_quantity || 1), unit: "R$ ", separator: ",", delimiter: ".") %>

  =======================
  Sistema Boamassa v0.1
  Powered by Novostek LLC
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .

app/views/comandas/index.html.erb
<h1 class="center-align"><b>Comandas</b></h1>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" r>
      Pesquisa
    </span>
    <div id="pesquisa" >
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <%= f.text_field :id_eq, placeholder: "Número" %>
      <%= f.text_field :client_nome_cont, placeholder: "Cliente" %>
          <div class="row">
            <div class="col s12 l3">
              <label >Data Inicial</label>
            <%= f.date_field :created_at_gteq, placeholder: "Data Inícial" %>
            </div>
            <div class="col s12 l3">
              <label >Data Final</label>
              <%= f.date_field :created_at_lteq, placeholder: "Data Final" %>
            </div>
            <div class="col s12 l3">
              <label >Paga</label>
              <select name="q[status_eq]" id="q_status_eq">
                <option value=""></option>
                <option value="true">SIM</option>
                <option value="false">NÂO</option>
              </select>
            </div>
          </div>
      <%= f.submit "Filtrar", class:"btn" %>
      <%= link_to  "Limpar", comandas_path, class:"btn", target:"_self" %>
      <% end %>
    </div>
  </div>
</div>
<div class="card-panel">
  <%= paginate(@comandas)  %>
</div>

<table class="card striped responsive-table">
  <thead>
  <tr>
    <th>Número</th>
    <th>Mesa</th>
    <th>Tipo</th>
    <th>Entrega</th>
    <th>Paga</th>
  </tr>
  </thead>

  <tbody>
    <% @comandas.each do |comanda| %>
      <tr>
        <td><%= link_to comanda,comanda %></td>
        <td><%= link_to comanda.dining_table,comanda.dining_table if comanda.dining_table.present?%></td>
        <td><%= comanda.tipo %></td>
        <td><%= comanda.entrega == true ? "SIM" : "NÃO" %></td>
        <td><%= comanda.status == true ? "SIM" : "NÃO" %></td>
        <td><%= link_to 'Excluir', comanda, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@comandas)  %>
</div>

<%= link_to '+ Cadastrar', new_comanda_path, class:"btn" %>