config/routes.rb
Rails.application.routes.draw do
  get 'google/callback'

  get 'google/redirect'

  get 'google/jobs'

  resources :configurations
  resources :app_configurations
  get 'taghere/menu'

  get 'taghere/set_table'
  get 'taghere/order'
  get 'taghere/balance'
  get 'taghere/garcon'
  get 'taghere/success'

  resources :employees do
    member do
      get "adiantamento"
    end
    collection do
      get "imprimir_adiantamento"
      get "deletar_vale"
    end
  end
  resources :couverts
  get 'garcon/chamadas'

  get 'garcon/pedido'

  get 'garcon/fechar_conta'

  devise_for :users
  resources :users
  resources :cancel_reasons
  resources :measures
  resources :pedido_extras
  resources :extras
  resources :payment_types
  resources :client_phones
  resources :clients do
    collection do
      get "check_cpf"
      get "credito"
    end
    member do
      get "crediario"
    end
  end
  resources :providers do
    collection do
      get "check_cpf"
    end
  end
  resources :ingredient_entraces
  resources :entrances
  resources :comandas do
    member do
      get "novo_pedido"
      get "concluir"
      get "pedido_simples"
      get "imprimir"
      get "imprimir_nogroup"
      get "calcular_taxa"
      get "inserir_couvert"
      get "fechar"
      get "calcular_desconto"

    end
    collection do
      get "enviar_pedido"
      get "dashboard"
      get "simples"
      get "caixa"
    end
  end
  resources :flavor_orders
  resources :product_orders do
    collection do
      get "atualiza_pedido"
    end
    member do
      get "change_comanda"
      get "cancelar"
      get "imprimir"
      get "concluir"
    end
  end
  resources :orders do
    member do
      get "change_comanda"
      get "cancelar"
      get "print"
    end
  end
  resources :dining_tables do
    collection do
      get "home"
    end
    member do
      get "comandas"
      get "unificar_comandas"
    end
  end
  resources :promotion_flavor_sizes
  resources :promotions
  resources :flavor_sizes do
    collection do
      get "produtos_por_categoria"
      get "retorna_sabores"
      get "retorna_adicionais"
    end
  end
  resources :ingredient_flavors
  resources :flavors
  resources :product_sizes
  resources :products
  resources :areas do
    collection do
      get "atualiza"
    end
  end
  resources :subgroups
  resources :product_groups
  resources :ingredients

  resources :sage_one do
    collection do
      get "url_callback"
    end
  end

  root "dining_tables#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_configuration.rb
# == Schema Information
#
# Table name: configurations
#
#  id         :integer          not null, primary key
#  key        :string
#  value      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class AppConfiguration < ApplicationRecord
  self.table_name = "configurations"
end

app/controllers/app_configurations_controller.rb
class AppConfigurationsController < ApplicationController
  before_action :set_configuration, only: [:show, :edit, :update, :destroy]

  # GET /configurations
  def index
    @q = AppConfiguration.ransack(params[:q])
    @configurations = @q.result.page(params[:page])
  end

  # GET /configurations/1
  def show
  end

  # GET /configurations/new
  def new
    @configuration = AppConfiguration.new
  end

  # GET /configurations/1/edit
  def edit
  end

  # POST /configurations
  def create
    @configuration = AppConfiguration.new(configuration_params)

    if @configuration.save
      redirect_to @configuration, notice: 'AppConfiguration was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /configurations/1
  def update
    if @configuration.update(configuration_params)
      redirect_to @configuration, notice: 'AppConfiguration was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /configurations/1
  def destroy
    @configuration.destroy
    redirect_to configurations_url, notice: 'AppConfiguration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_configuration
      @configuration = AppConfiguration.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def configuration_params
      params.require(:app_configuration).permit(:key, :value)
    end
end

app/views/app_configurations/_form.html.erb
<%= form_for(configuration) do |f| %>
  <% if configuration.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5>Resolva os problemas a seguir antes de Salvar:</h5>

      <ul>
      <% configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">
  
  <div class="input-field">

    <%= f.label :key %>
    <%= f.text_field :key %>
    
  </div>

  <div class="input-field">

    <%= f.label :value %>
    <%= f.text_field :value %>
    
  </div>

</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn" %>
  </div>
<% end %>

app/views/app_configurations/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição</h4>
</div>

<%= render 'form', configuration: @configuration %>

app/views/app_configurations/index.html.erb
<div class="card">  
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <%# f.text_field :name_cont, placeholder: "Pesquisar..." %>
      <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>

<table class="card striped responsive-table">
  <thead>
    <tr>
            <th>Key</th>
            <th>Value</th>
          </tr>
  </thead>

  <tbody>
    <% @configurations.each do |configuration| %>
    <tr>
              
          <td><%= link_to configuration.key,configuration %></td>
        
              

          <td><%= configuration.value %></td>
        
          </tr>
    <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@configurations)  %>
</div>

<%= link_to '+ Cadastrar', new_configuration_path, class:"btn" %>

app/views/app_configurations/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro</h4>
</div>

<%= render 'form', configuration: @configuration %>

app/views/app_configurations/show.html.erb
<div class="card-panel">
	
<p>
  <strong>Key:</strong>
  <%= @configuration.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @configuration.value %>
</p>

</div>
<%= link_to 'Voltar', configurations_path, class:"btn" %>