config/routes.rb
Rails.application.routes.draw do
  get 'google/callback'

  get 'google/redirect'

  get 'google/jobs'

  resources :configurations
  resources :app_configurations
  get 'taghere/menu'

  get 'taghere/set_table'
  get 'taghere/order'
  get 'taghere/balance'
  get 'taghere/garcon'
  get 'taghere/success'

  resources :employees do
    member do
      get "adiantamento"
    end
    collection do
      get "imprimir_adiantamento"
      get "deletar_vale"
    end
  end
  resources :couverts
  get 'garcon/chamadas'

  get 'garcon/pedido'

  get 'garcon/fechar_conta'

  devise_for :users
  resources :users
  resources :cancel_reasons
  resources :measures
  resources :pedido_extras
  resources :extras
  resources :payment_types
  resources :client_phones
  resources :clients do
    collection do
      get "check_cpf"
      get "credito"
    end
    member do
      get "crediario"
    end
  end
  resources :providers do
    collection do
      get "check_cpf"
    end
  end
  resources :ingredient_entraces
  resources :entrances
  resources :comandas do
    member do
      get "novo_pedido"
      get "concluir"
      get "pedido_simples"
      get "imprimir"
      get "imprimir_nogroup"
      get "calcular_taxa"
      get "inserir_couvert"
      get "fechar"
      get "calcular_desconto"

    end
    collection do
      get "enviar_pedido"
      get "dashboard"
      get "simples"
      get "caixa"
    end
  end
  resources :flavor_orders
  resources :product_orders do
    collection do
      get "atualiza_pedido"
    end
    member do
      get "change_comanda"
      get "cancelar"
      get "imprimir"
      get "concluir"
    end
  end
  resources :orders do
    member do
      get "change_comanda"
      get "cancelar"
      get "print"
    end
  end
  resources :dining_tables do
    collection do
      get "home"
    end
    member do
      get "comandas"
      get "unificar_comandas"
    end
  end
  resources :promotion_flavor_sizes
  resources :promotions
  resources :flavor_sizes do
    collection do
      get "produtos_por_categoria"
      get "retorna_sabores"
      get "retorna_adicionais"
    end
  end
  resources :ingredient_flavors
  resources :flavors
  resources :product_sizes
  resources :products
  resources :areas do
    collection do
      get "atualiza"
    end
  end
  resources :subgroups
  resources :product_groups
  resources :ingredients

  resources :sage_one do
    collection do
      get "url_callback"
    end
  end

  root "dining_tables#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entrance.rb
# == Schema Information
#
# Table name: entrances
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  provider_id :integer
#
# Indexes
#
#  index_entrances_on_provider_id  (provider_id)
#
# Foreign Keys
#
#  fk_rails_...  (provider_id => providers.id)
#

class Entrance < ApplicationRecord
  has_paper_trail
  has_many :ingredient_entraces
  belongs_to :provider

  accepts_nested_attributes_for :ingredient_entraces, allow_destroy: true
  
  after_create :atualizar_estoque

  #atualiza o estoque dos ingredientes
  def atualizar_estoque
    self.ingredient_entraces.each do |i|
      p = Ingredient.find(i.ingredient_id)
      p.quantity += i.quantity
      p.save
    end
  end
end

app/controllers/entrances_controller.rb
class EntrancesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_entrance, only: [:show, :edit, :update, :destroy]
  before_action :set_combos, only: [:new,:edit,:create]

  # GET /entrances
  def index
    @q = Entrance.all.ransack(params[:q])
    @entrances = @q.result.page(params[:page])
  end

  # GET /entrances/1
  def show
  end

  # GET /entrances/new
  def new
    @entrance = Entrance.new

  end

  # GET /entrances/1/edit
  def edit
  end

  # POST /entrances
  def create
    @entrance = Entrance.new(entrance_params)

    if @entrance.save
      redirect_to @entrance, notice: 'Entrada criada com sucesso!'
    else
      render :new
    end
  end

  # PATCH/PUT /entrances/1
  def update
    if @entrance.update(entrance_params)
      redirect_to @entrance, notice: 'Entrada atualizada com sucesso!'
    else
      render :edit
    end
  end

  # DELETE /entrances/1
  def destroy
    begin
      @entrance.destroy
      redirect_to entrances_url, notice: 'Entrada excluída com sucesso!'
    rescue
      redirect_to entrances_url, notice: 'Entrada já está vinculada!'
    end

  end

  private
  def set_combos
    @ingredients = Ingredient.all.sort_by{|e| e.name }.map{|a| [a.name,a.id]}
    @providers = Provider.all.sort_by{|e| e.name }.map{|a| [a.name,a.id]}
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_entrance
      @entrance = Entrance.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entrance_params
      params.require(:entrance).permit(:provider_id,ingredient_entraces_attributes:[:id,:entrance_id,:ingredient_id,:value,:quantity])
    end
end

app/helpers/entrances_helper.rb
module EntrancesHelper
end

app/views/entrances/_form.html.erb
<%= nested_form_for(entrance) do |f| %>
  <% if entrance.errors.any? %>
    <div id="error_explanation" class="card-panel red white-text">
      <h5>Resolva os problemas a seguir antes de Salvar:</h5>

      <ul>
      <% entrance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-panel">

  <div class="input">
    <%= f.label :provider_id, "Fornecedor" %>
    <%= f.select :provider_id, @providers, {prompt:true},{class:"browser-default chosen-select"}  %>
  </div>

  <div class="card">
    <div class="card-content">
      <span class="card-title">Produtos de Entrada</span>


      <%= f.fields_for :ingredient_entraces do |s| %>
          <div class="row" >
            <div class="input col s6">
              <%= s.label :ingredient_id, "Ingrediente" %>
              <%= s.select :ingredient_id, @ingredients, {prompt:true},{class:"browser-default select2"}  %>
            </div>
            <div class="input-field col s2">
              <%= s.label :quantity, "Quantidade" %>
              <%= s.text_field :quantity %>

            </div>
            <div class="input-field col s2">
              <%= s.label :value, "Valor" %>
              <%= s.number_field :value, step: :any %>

            </div>
            <div class="col s2">
              <%= s.link_to_remove "Remover" %>
            </div>
          </div>
      <% end %>
    </div>
    <div class="card-action">
      <p><%= f.link_to_add "Novo Produto", :ingredient_entraces %></p>
    </div>

  </div>
  
</div>
  <div class="actions">
    <%= f.submit "Salvar", class:"btn",target:"_self" %>
    <%= link_to "Voltar", entrances_path, class:"btn",target:"_self" %>
  </div>
<% end %>

app/views/entrances/edit.html.erb
<div class="card-panel center">
	<h4>Formulário de Edição - Notas de Entrada</h4>
</div>

<%= render 'form', entrance: @entrance %>

app/views/entrances/index.html.erb
<h1 class="center-align"><b>Notas de Entrada</b></h1>
<div class="card">
  <div class="card-content">
    <span class="card-title grey-text text-darken-4" onclick="toogle_div('#pesquisa')">
      Pesquisa
    </span>
    <div id="pesquisa" class="not-show">
      <%= search_form_for @q, url: request.env['PATH_INFO'] do |f|  %>
      <%= f.text_field :provider_name_or_provider_inscricao_cont, placeholder: "Fornecedor" %>
      <%= f.submit "Filtrar", class:"btn" %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to '+ Cadastrar', new_entrance_path, class:"btn", target: "_self" %>
<table class="card striped responsive-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Fonecedor</th>
      <th>Data</th>
    </tr>
  </thead>

  <tbody>
    <% @entrances.each do |entrance| %>
    <tr>
      <td><%= link_to entrance.id, entrance %></td>
      <td><%= entrance.provider %></td>
      <td><%= entrance.created_at %></td>
      <td><%= link_to 'Excluir', entrance, method: :delete, data: { confirm: 'Deseja realmente excluir?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="card-panel">
  <%= paginate(@entrances)  %>
</div>

<%= link_to '+ Cadastrar', new_entrance_path, class:"btn", target: "_self" %>

app/views/entrances/new.html.erb
<div class="card-panel center">
	<h4>Formulário de Cadastro - Notas de entrada</h4>
</div>

<%= render 'form', entrance: @entrance %>

app/views/entrances/show.html.erb
<h1 class="center-align"><b>Entrada</b></h1>
<div class="card-panel">
  <p>
    <strong>Fornecedor:</strong>
    <%= link_to @entrance.provider, @entrance.provider %>
  </p>
  <p>
    <strong>Data:</strong>
    <%= @entrance.created_at %>
  </p>

  <div class="card">
    <div class="card-content">
      <span class="card-title"><b>Produtos de Entrada</b>
      </span>
      <table>
        <tr>
          <th>Produto</th>
          <th>Quantidade</th>
          <th>Valor</th>
        </tr>
        <% @entrance.ingredient_entraces.each do |i| %>
          <tr>
            <td><%= i.ingredient %></td>
            <td><%= i.quantity %></td>
            <td><%= number_to_currency(i.value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
          </tr>
        <% end %>

      </table>
    </div>
  </div>
</div>
<%= link_to 'Voltar', entrances_path, class:"btn",target:"_self" %>